- hosts: all
  become: true

  tasks:

    - name: Update apt cache
      apt:
        update_cache: true
      when: ansible_pkg_mgr == "apt"

    - name: Update dnf pkgs
      dnf:
        update_cache: true
      when: ansible_pkg_mgr == "dnf"